# Generated by Django 2.2.6 on 2019-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191002_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='subcribed',
            field=models.ManyToManyField(blank=True, related_name='subcribed_to', to='blog.BlogAuthor', verbose_name='subcribed'),
        ),
    ]
