# Generated by Django 2.2.6 on 2019-10-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogauthor_subcribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='subcribed',
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to='blog.BlogAuthor', verbose_name='subscribed'),
        ),
    ]
