# Generated by Django 2.2.6 on 2019-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191002_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='_blogauthor_subscribed_+', to='blog.BlogAuthor', verbose_name='subscribed'),
        ),
    ]
