# Generated by Django 2.2.6 on 2019-10-04 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20191003_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAuthor',
            new_name='Author',
        ),
    ]
